public class BainMaca {


    //TODO
    public static void main(String[] args) {
        {
            System.out.println("Move thfddsis 1");

            //TODO


            sxxzz



            System.out.println("rrrrdino");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxcxzcxzzxfdcxzczxcxzdsis 1");


            Az ~``AA



            System.out.println("Do not mfsdodfgdfgdfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifsscxfsdfsdzzcxdfdsdfzxczxcdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not czxczmfdsfsdfdasaSassdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffadasasdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsasdasdadsasdfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdscdsadaszxczxdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfxcxzddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsisxcvcx 1");
            System.out.println("Do not mfsdodfzxcxzcdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");




            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



            System.out.println("fdsfds");
            System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
            System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
            System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
            System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
            System.out.println("Move thfczxddsis 1");
            System.out.println("Do not mfsdodfdfdveee 1");
            System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");




        }
    }
}
