public class KlupaGlupa {
    public static void main(String[] args) {
System.out.println("Demon");
    }

    @Override
    public String toString() {
        return "papara2";


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdvdgdgeee 1");
        System.out.println("Move thifssdfdsdgdfdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsisfdgdf 1");
        System.out.println("Do not mfsdoddfgdffdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");


        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");



        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");





        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");




        System.out.println("fdsfds");
        System.out.println("Move tczxcxzhifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thzxxcvcxxcczxfdcxzczxcxzdsis 1");
        System.out.println("Do not mfsdodfdczczxfdssdfdsddsasfdveee 1");
        System.out.println("Move thifssdfdsdfdfdsfdsfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfsdfsddsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfdsfsdfdssdodfdfdveee 1");
        System.out.println("Move thifssdfdsdffffdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move tdsashifssdfdsdfdfdfdCSDfdsfsdfs too 1");
        System.out.println("Move thfczxddsis 1");
        System.out.println("Do not mfsdodfdfdveee 1");
        System.out.println("Move thifssdfdsdfdfdfdCSDfdsfsdfs too 1");

    }
}
